import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
fs.mkdirSync('tests/.generated',{recursive:true});
for(const [src,dst] of [['shared/domain.ts','domain.mjs'],['lib/service.ts','service.mjs']]){let code=fs.readFileSync(src,'utf8').replace("'../shared/domain'","'./domain.mjs'");fs.writeFileSync('tests/.generated/'+dst,ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const {seedWorkspace}=await import('./.generated/domain.mjs');
const {applyAction,publicWorkspace}=await import('./.generated/service.mjs');
function ready(){const s=seedWorkspace();const c=s.complaints[1];c.afterMedia=['test-evidence'];return {s,c};}
test('admin cannot close a complaint directly',async()=>{const {s,c}=ready();c.status='Resolution Proposed';await assert.rejects(applyAction(s,{action:'transition',id:c.id,status:'Closed',note:'Close complaint'},'admin'),/OTP/);});
test('resolution proposal requires evidence',async()=>{const {s,c}=ready();c.afterMedia=[];await assert.rejects(applyAction(s,{action:'transition',id:c.id,status:'Resolution Proposed',note:'The road has been repaired.'},'admin'),/evidence/);});
test('resident cannot perform admin work',async()=>{const {s,c}=ready();await assert.rejects(applyAction(s,{action:'edit',id:c.id,priority:'High'},'resident'),/Administrator/);});
test('verified closure, incorrect attempt, replay rejection and dispute',async()=>{const {s,c}=ready();await applyAction(s,{action:'transition',id:c.id,status:'Resolution Proposed',note:'Repair is complete; after-work photo attached.'},'admin',100000);const code=await applyAction(s,{action:'preview-closure-code',id:c.id},'resident',100001);assert.equal((await applyAction(s,{action:'verify-closure',id:c.id,code:'wrong'},'resident',100002)).error,'Incorrect verification code.');assert.equal(c.status,'Resolution Proposed');await applyAction(s,{action:'verify-closure',id:c.id,code:code.demoCode},'resident',100003);assert.equal(c.status,'Closed');assert.ok(!s.challenges[c.id]);await assert.rejects(applyAction(s,{action:'verify-closure',id:c.id,code:code.demoCode},'resident',100004));await applyAction(s,{action:'dispute',id:c.id,note:'The same issue persists at the location.'},'resident',100005);assert.equal(c.status,'Reopened');assert.equal(s.audit.length,5);});
test('OTP expires and cannot be resent immediately',async()=>{const {s,c}=ready();c.status='Resolution Proposed';await applyAction(s,{action:'issue-closure-code',id:c.id},'resident',100000);const code=await applyAction(s,{action:'preview-closure-code',id:c.id},'resident',100000);await assert.rejects(applyAction(s,{action:'issue-closure-code',id:c.id},'resident',100001),/60 seconds/);await assert.rejects(applyAction(s,{action:'verify-closure',id:c.id,code:code.demoCode},'resident',400001),/expired/);});
test('five wrong attempts lock a challenge',async()=>{const {s,c}=ready();c.status='Resolution Proposed';const code=await applyAction(s,{action:'issue-closure-code',id:c.id},'resident',100000);for(let i=0;i<5;i++)await applyAction(s,{action:'verify-closure',id:c.id,code:'wrong'},'resident',100001+i);await assert.rejects(applyAction(s,{action:'verify-closure',id:c.id,code:code.demoCode},'resident',100020),/locked/);});
test('challenge hashes never appear in workspace payload',async()=>{const {s,c}=ready();c.status='Resolution Proposed';await applyAction(s,{action:'issue-closure-code',id:c.id},'resident');assert.equal('challenges' in publicWorkspace(s),false);});
test('privileged override fails closed',async()=>{const {s,c}=ready();await assert.rejects(applyAction(s,{action:'override-close',id:c.id},'admin'),/disabled/);});
test('admin closure request automatically issues an OTP without exposing it to admin',async()=>{const {s,c}=ready();const result=await applyAction(s,{action:'transition',id:c.id,status:'Resolution Proposed',note:'The repair is complete and evidence is attached.'},'admin',100000);assert.ok(s.challenges[c.id]);assert.equal(result.demoCode,undefined);assert.equal(c.status,'Resolution Proposed');assert.equal(result.channel,'WhatsApp');assert.equal(result.delivery,'setup-required');await assert.rejects(applyAction(s,{action:'preview-closure-code',id:c.id},'admin',100001),/Resident/);const code=await applyAction(s,{action:'preview-closure-code',id:c.id},'resident',100001);assert.match(code.demoCode,/^\d{6}$/);assert.ok(s.communications.every(m=>m.channel==='WhatsApp'&&!JSON.stringify(m).includes(code.demoCode)));});
test('acknowledgement has the same unique reference as the stored complaint',async()=>{const {s}=ready();const body={action:'create',title:'Sample broken pathway',description:'Sample pathway beside the demo park is damaged.',category:'Road & Footpath',locality:'Demo locality',lat:26,lng:75,media:['test'],consent:true};const a=await applyAction(s,body,'resident');const b=await applyAction(s,body,'resident');assert.notEqual(a.referenceNumber,b.referenceNumber);assert.equal(a.referenceNumber,a.id);assert.ok(s.communications.find(m=>m.complaintId===a.id).message.includes(a.referenceNumber));assert.equal(s.communications[0].channel,'WhatsApp');assert.match(s.communications[0].status,/Not sent/);});
test('complaint requires photo, location and explicit consent',async()=>{const {s}=ready();const body={action:'create',title:'A damaged pathway',description:'Damaged footpath beside the public park.',category:'Road & Footpath',locality:'Gandhi Nagar',lat:26.91,lng:75.78,media:['test-evidence'],consent:true};await assert.rejects(applyAction(s,{...body,consent:false},'resident'),/consent/);await assert.rejects(applyAction(s,{...body,media:[]},'resident'),/photographs/);await assert.rejects(applyAction(s,{...body,lat:100},'resident'),/coordinates/);const result=await applyAction(s,body,'resident');assert.equal(s.complaints[0].id,result.id);assert.equal(s.complaints[0].status,'Submitted');});
