'use client';
import {useState} from 'react';
import {categoryIcons,type IssueCategory} from '@/shared/domain';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
type Props={categories:IssueCategory[];busy:boolean;act:(body:Record<string,unknown>)=>Promise<unknown>};
export default function CategoryManager({categories,busy,act}:Props){
 const [draft,setDraft]=useState<Partial<IssueCategory>|null>(null);const [error,setError]=useState('');const [saved,setSaved]=useState('');
 const sorted=[...categories].sort((a,b)=>a.sortOrder-b.sortOrder||a.nameEn.localeCompare(b.nameEn));
 function edit(category?:IssueCategory){setError('');setSaved('');setDraft(category?{...category}:{nameEn:'',nameHi:'',icon:'ellipsis-horizontal',color:'#247a57',enabled:true,sortOrder:Math.max(-1,...categories.map(c=>c.sortOrder))+1});}
 return <section className="panel category-manager"><div className="panel-heading"><div><h2>Issue categories · समस्या के प्रकार</h2><p>The mobile app loads these categories from the server. Changes do not require an app release.</p></div><button className="button primary" onClick={()=>edit()}>Add category</button></div>{saved&&<p className="info-note" role="status">{saved}</p>}<Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>English</TableHead><TableHead>Hindi</TableHead><TableHead>Visibility</TableHead><TableHead/></TableRow></TableHeader><TableBody>{sorted.map(c=><TableRow key={c.id}><TableCell>{c.sortOrder}</TableCell><TableCell><span style={{color:c.color}}>● </span>{c.nameEn}</TableCell><TableCell>{c.nameHi}</TableCell><TableCell>{c.enabled?'Active':'Hidden from new reports'}</TableCell><TableCell><button className="text-button" onClick={()=>edit(c)} aria-label={`Edit ${c.nameEn}`}>Edit</button></TableCell></TableRow>)}</TableBody></Table>{!sorted.length&&<p className="empty-state">No categories configured. Add one to enable citizen reporting.</p>}<p className="muted" style={{padding:20}}>Disable a category to stop new reports. Existing complaints retain their original category and history.</p>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open)setDraft(null);}}><DialogContent><DialogHeader><DialogTitle>{draft?.id?'Edit issue category':'Add issue category'}</DialogTitle><DialogDescription>Configure the names, icon, display order and availability shown to citizens.</DialogDescription></DialogHeader>{draft&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();setError('');try{await act({action:'save-category',category:draft});setDraft(null);setSaved('Category saved. Citizens see it when they open or refresh the issue-type screen.');}catch(e){setError((e as Error).message);}}}><label>English name<input required minLength={2} maxLength={80} value={draft.nameEn} onChange={e=>setDraft({...draft,nameEn:e.target.value})}/></label><label>Hindi name<input required minLength={2} maxLength={80} value={draft.nameHi} onChange={e=>setDraft({...draft,nameHi:e.target.value})}/></label><label>Icon<Select value={draft.icon} onValueChange={icon=>setDraft({...draft,icon})}><SelectTrigger aria-label="Category icon"><SelectValue/></SelectTrigger><SelectContent>{categoryIcons.map(icon=><SelectItem key={icon} value={icon}>{icon.replaceAll('-',' ')}</SelectItem>)}</SelectContent></Select></label><div className="two-fields"><label>Icon color<input type="color" aria-label="Icon color" value={draft.color} onChange={e=>setDraft({...draft,color:e.target.value})}/></label><label>Display order<input type="number" min={0} max={9999} required value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})}/></label></div><label className="consent"><Switch checked={draft.enabled} onCheckedChange={enabled=>setDraft({...draft,enabled})}/><span>Available for new complaints</span></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy} className="button primary">{busy?'Saving…':'Save category'}</button></form>}</DialogContent></Dialog></section>;
}
