'use client';
import {useEffect,useState} from 'react';
import {permissions,rolePresets,type AdminRole,type Permission} from '@/shared/access';
import {defaultMunicipality,type Classified,type Place,type Municipality} from '@/shared/community';
import type {Workspace} from '@/shared/domain';
import {uploadPhoto} from './use-workspace';

type Act=(body:Record<string,unknown>)=>Promise<any>;
const blankAd=():Classified=>({id:'',title:'',titleHi:'',description:'',descriptionHi:'',advertiser:'',contactPhone:'',url:'',imageId:'',startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+30*86400000).toISOString(),status:'draft',publishedAt:null});
const blankPlace=():Place=>({id:'',name:'',nameHi:'',description:'',descriptionHi:'',address:'',hours:'',sourceUrl:'',mapUrl:'',imageId:'',published:false,sortOrder:10});
function Field({label,value,onChange,area=false,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean;type?:string;required?:boolean}){return <label>{label}{area?<textarea rows={5} required={required} value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} required={required} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
function Photo({id,onChange}:{id:string;onChange:(v:string)=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <div>{id&&<img alt="Content preview" src={`/api/media?id=${id}`} style={{maxHeight:160,borderRadius:10}}/>}<label>Photograph<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{onChange(await uploadPhoto(file));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{busy&&<p>Uploading…</p>}{error&&<p role="alert" className="error">{error}</p>}{id&&<button type="button" className="text-button" onClick={()=>onChange('')}>Remove photograph</button>}</div>;}
export default function CommunityPanel({page,data,act,busy}:{page:string;data:Workspace;act:Act;busy:boolean}){
 const [ad,setAd]=useState<Classified|null>(null),[place,setPlace]=useState<Place|null>(null),[city,setCity]=useState<Municipality>(data.municipality??defaultMunicipality()),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function run(body:Record<string,unknown>){setError('');setMessage('');try{await act(body);setMessage('Changes saved.');return true;}catch(e){setError((e as Error).message);return false;}}
 return <section className="admin-section">{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="info-note">{message}</p>}
 {page==='Classifieds'&&<><div className="section-title"><div><h2>Community classifieds</h2><p>Draft an ad, then publish it to the mobile app and opted-in residents’ inboxes.</p></div><button className="button primary" onClick={()=>setAd(blankAd())}>＋ New classified</button></div><div className="notice-grid">{data.classifieds?.map(a=><article className="panel notice-card" key={a.id}>{a.imageId&&<img src={`/api/media?id=${a.imageId}`} alt="" style={{height:140,width:'100%',objectFit:'cover',borderRadius:8}}/>}<span className="notice-type">{a.status}{new Date(a.endsAt)<new Date()?' · Expired':''}</span><h3>{a.title}</h3><p>{a.advertiser}</p><small>Until {new Date(a.endsAt).toLocaleString()}</small><div className="action-buttons"><button className="button" disabled={busy} onClick={()=>setAd({...a})}>Edit</button>{a.status!=='published'&&<button className="button primary" disabled={busy} onClick={()=>void run({action:'publish-classified',id:a.id,status:'published'})}>Publish & notify</button>}{a.status==='published'&&<button className="button" disabled={busy} onClick={()=>void run({action:'publish-classified',id:a.id,status:'archived'})}>Archive</button>}</div></article>)}</div>{!data.classifieds?.length&&<p className="empty-state">No advertisements yet. Create your first classified.</p>}
 {ad&&<form className="panel settings-card form-stack" onSubmit={async e=>{e.preventDefault();if(await run({action:'save-classified',classified:ad}))setAd(null);}}><h2>{ad.id?'Edit classified':'New classified'}</h2><p>Saving creates a draft. Publishing creates one inbox notification; republishing does not send duplicates.</p>{(['title','titleHi','advertiser','description','descriptionHi','contactPhone','url'] as const).map(key=><Field key={key} label={{title:'Title (English)',titleHi:'Title (हिन्दी)',advertiser:'Advertiser / organisation',description:'Description (English)',descriptionHi:'Description (हिन्दी)',contactPhone:'Contact phone',url:'Website (HTTPS)'}[key]} value={ad[key]} required={['title','description','advertiser'].includes(key)} area={key.startsWith('description')} onChange={v=>setAd({...ad,[key]:v})}/>)}<div className="two-fields">{(['startsAt','endsAt'] as const).map(key=><Field key={key} label={key==='startsAt'?'Starts at':'Expires at'} type="datetime-local" required value={new Date(+new Date(ad[key])-new Date(ad[key]).getTimezoneOffset()*60000).toISOString().slice(0,16)} onChange={v=>{if(v)setAd({...ad,[key]:new Date(v).toISOString()});}}/>)}</div><Photo id={ad.imageId} onChange={v=>setAd({...ad,imageId:v})}/><div className="action-buttons"><button disabled={busy} className="button primary">Save draft</button><button type="button" className="button" onClick={()=>setAd(null)}>Cancel</button></div></form>}<p className="muted">In-app notifications are active. Phone push delivery needs a configured Expo project and device registration.</p></>}
 {page==='City & places'&&<><form className="panel settings-card form-stack" onSubmit={async e=>{e.preventDefault();await run({action:'save-municipality',municipality:city});}}><h2>Know your municipality</h2><p>Publish verified local information in English and Hindi.</p>{(['name','nameHi','district','state','about','aboutHi','history','historyHi','sourceUrl'] as const).map(key=><Field key={key} label={{name:'Municipality name',nameHi:'नगरपालिका / नगरपरिषद का नाम',district:'District',state:'State',about:'About (English)',aboutHi:'परिचय (हिन्दी)',history:'History (English)',historyHi:'इतिहास (हिन्दी)',sourceUrl:'Official / historical source (HTTPS)'}[key]} value={city[key]} area={['about','aboutHi','history','historyHi'].includes(key)} required={['name','district','state'].includes(key)} onChange={v=>setCity({...city,[key]:v})}/>)}<label><input type="checkbox" checked={city.published} onChange={e=>setCity({...city,published:e.target.checked})}/> Publish in citizen app</label><button disabled={busy} className="button primary">Save municipality</button></form><div className="section-title"><div><h2>Places to visit</h2><p>Local sights, heritage and useful visitor information.</p></div><button className="button primary" onClick={()=>setPlace(blankPlace())}>＋ Add a place</button></div><div className="notice-grid">{data.places?.map(p=><article className="panel notice-card" key={p.id}><span className="notice-type">{p.published?'Published':'Draft'}</span><h3>{p.name}</h3><p>{p.address}</p><button className="button" onClick={()=>setPlace({...p})}>Edit place</button></article>)}</div>{place&&<form className="panel settings-card form-stack" onSubmit={async e=>{e.preventDefault();if(await run({action:'save-place',place}))setPlace(null);}}><h2>{place.id?'Edit place':'Add a place'}</h2>{(['name','nameHi','description','descriptionHi','address','hours','mapUrl','sourceUrl'] as const).map(key=><Field key={key} label={{name:'Name (English)',nameHi:'नाम (हिन्दी)',description:'Description (English)',descriptionHi:'विवरण (हिन्दी)',address:'Address',hours:'Visiting hours',mapUrl:'Map link (HTTPS)',sourceUrl:'Source (HTTPS)'}[key]} value={place[key]} required={['name','description','address'].includes(key)} area={key.startsWith('description')} onChange={v=>setPlace({...place,[key]:v})}/>)}<Photo id={place.imageId} onChange={v=>setPlace({...place,imageId:v})}/><Field label="Display order" type="number" value={String(place.sortOrder)} onChange={v=>setPlace({...place,sortOrder:Number(v)})}/><label><input type="checkbox" checked={place.published} onChange={e=>setPlace({...place,published:e.target.checked})}/> Published</label><div className="action-buttons"><button disabled={busy} className="button primary">Save place</button><button type="button" className="button" onClick={()=>setPlace(null)}>Cancel</button></div></form>}</>}
 {page==='Admin access'&&<AccessManager act={act} busy={busy}/>}
 </section>;
}
type Admin={email:string;role:AdminRole;permissions:Permission[];active:boolean};
function AccessManager({act,busy}:{act:Act;busy:boolean}){const [admins,setAdmins]=useState<Admin[]>([]),[entry,setEntry]=useState<Admin>({email:'',role:'Complaint Officer',permissions:[...rolePresets['Complaint Officer']],active:true}),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/workspace?section=admins',{signal:controller.signal}).then(async r=>{const j=await r.json() as {error?:string;admins:Admin[]};if(!r.ok)throw new Error(j.error);setAdmins(j.admins);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 return <><div className="section-title"><div><h2>People & permissions</h2><p>Super Admins grant access by verified sign-in email. Changes apply on the next server request.</p></div></div><p className="info-note">The founding Super Admin retains access. Private hosted preview access must also be granted at the hosting layer; production admin sign-in is still to be configured.</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}<div className="notice-grid">{admins.map(a=><article className="panel notice-card" key={a.email}><span className="notice-type">{a.active?'Active':'Disabled'} · {a.role}</span><h3>{a.email}</h3><p>{a.permissions.length} permissions</p><button className="button" onClick={()=>setEntry({...a})}>Manage access</button></article>)}</div><form className="panel settings-card form-stack" onSubmit={async e=>{e.preventDefault();setError('');setMessage('');try{const r=await act({action:'save-admin',admin:entry});setAdmins(r.admins);setMessage('Administrator access saved.');}catch(e){setError((e as Error).message);}}}><h2>Grant or update access</h2><Field label="Sign-in email" value={entry.email} type="email" required onChange={v=>setEntry({...entry,email:v})}/><label>Persona / role<select value={entry.role} onChange={e=>{const role=e.target.value as AdminRole;setEntry({...entry,role,permissions:[...rolePresets[role]]});}}>{Object.keys(rolePresets).map(role=><option key={role}>{role}</option>)}</select></label><fieldset><legend>Allowed actions</legend>{permissions.map(p=><label key={p} style={{display:'flex',gap:10,margin:'10px 0'}}><input type="checkbox" checked={entry.permissions.includes(p)} disabled={entry.role!=='Custom'||p==='admins.manage'} onChange={e=>setEntry({...entry,permissions:e.target.checked?[...entry.permissions,p]:entry.permissions.filter(x=>x!==p)})}/>{p.replace('.',' · ')}</label>)}</fieldset><label><input type="checkbox" checked={entry.active} onChange={e=>setEntry({...entry,active:e.target.checked})}/> Account active</label>{entry.role==='Super Admin'&&<p className="info-note">This role can grant and revoke other administrators’ access.</p>}<button disabled={busy} className="button primary">Save access</button></form></>;
}

