'use client';
import { useState, useEffect, useMemo } from 'react';
import { LayoutDashboard, ClipboardList, Users, ChartNoAxesCombined, Megaphone, Settings, ShieldCheck, MapPin, Search, ArrowRight, Clock3, CheckCheck, Sprout, ChevronRight, CalendarDays, SlidersHorizontal, Smartphone, Download, MapPinned, Tags } from 'lucide-react';
import { Sidebar, SidebarContent, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarProvider, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Table, TableBody, TableHead, TableHeader, TableRow, TableCell } from '@/components/ui/table';
import { statuses, type Complaint } from '@/shared/domain';
import CommunityPanel from './community-panels';
import CategoryManager from './category-manager';
import ActivitiesManager from './activities-manager';
import CategoryChart from './category-chart';
import ActivityChart,{activityCaption} from './activity-chart';
import DateRangeControl from './date-range';
import {ALL_WARDS,filterByWard,resolveWardFilter,showWardFilter,wardFilterOptions} from '@/lib/complaint-wards';
import {complaintFilterOptions,complaintFilterSpec} from '@/lib/complaint-filters';
import {DEFAULT_PRESET,RANGE_STORAGE_KEY,bucketUnit,dayCount,filterByRange,makeRange,parseStoredRange,rangeLabel,serializeRange,summarize,type DateRange} from '@/lib/date-range';
import {type Permission} from '@/shared/access';
import {useWorkspace} from './use-workspace';
import {LoadingWorkspace,ComplaintDetail,Choice,WardFilter,AdminPanel,csvDownload} from './admin-panels';
import {FilterToolbar,FilterEmpty,ShowMore,usePaged,applyFilters,emptyFilters,filterKey,hasActiveFilters,type FilterDef,type FilterState} from './form-bits';
import './content-tables.css'; // the shared filter toolbar (FilterToolbar in form-bits.tsx) is styled there
import AdminUsersManager from './admin-users-manager';
import ResidentsManager from './residents-manager';
import {UserMenu} from './admin-login';
import MyProfile from './my-profile';
export function StatusBadge({status}:{status:string}) { return <span className={`status status-${status.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{status}</span>; }
/** The complaint rows shared by Overview (latest five) and the Complaints page. The ward line shows when the workspace has two or more wards; the department line only on the Complaints page. */
function ComplaintRows({rows,showWard,showDepartment=false,onOpen}:{rows:Complaint[];showWard:boolean;showDepartment?:boolean;onOpen:(id:string)=>void}){return <Table><TableHeader><TableRow><TableHead>COMPLAINT</TableHead><TableHead>LOCALITY</TableHead><TableHead>STATUS</TableHead><TableHead>PRIORITY</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.map(c=><TableRow key={c.id}><TableCell><button className="complaint-title" onClick={()=>onOpen(c.id)}>{c.title}</button><small className="complaint-id">{c.id}</small>{showDepartment&&<small className="complaint-id">{c.assignee?`Department: ${c.assignee}`:'Unassigned'}</small>}</TableCell><TableCell><span className="locality"><MapPin size={14}/>{c.locality}</span>{showWard&&<small className={`ward-line${c.wardLabel?'':' none'}`}>{c.wardLabel||'Ward not recorded'}</small>}</TableCell><TableCell><StatusBadge status={c.status}/></TableCell><TableCell><span className={`priority priority-${c.priority.toLowerCase()}`}>{c.priority}</span></TableCell><TableCell><button aria-label={`Open ${c.id}`} onClick={()=>onOpen(c.id)}><ChevronRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>;}
// ADMINISTRATION order: wards first (people live in wards), then departments and the categories that belong to them, then resident-facing content and users.
const nav=[['Overview',LayoutDashboard],['Complaints',ClipboardList],['Reports',ChartNoAxesCombined],['Wards',MapPinned],['Departments',Users],['Categories',Tags],['Classifieds',Megaphone],['Activities',CalendarDays],['Announcements',Megaphone],['City & places',MapPin],['App users',Smartphone],['Admin Users',ShieldCheck],['App settings',SlidersHorizontal],['Settings',Settings]] as const;
/** Pages in the WORKSPACE group; every other page sits under ADMINISTRATION. */
const WORKSPACE_PAGES=['Overview','Complaints','Reports'];
const pagePermission:Record<string,Permission>={'Wards':'settings.manage','Overview':'complaints.read','Complaints':'complaints.read','Departments':'complaints.read','Reports':'complaints.read','Announcements':'announcements.manage','Categories':'categories.manage','Classifieds':'classifieds.manage','Activities':'activities.manage','City & places':'city.manage','App users':'residents.manage','Admin Users':'admins.manage','App settings':'appconfig.manage','Settings':'settings.manage'};
/** Sidebar entry: choosing a page also closes the side panel on mobile. */
function NavItemButton({active,onSelect,children}:{active:boolean;onSelect:()=>void;children:React.ReactNode}){const {isMobile,setOpenMobile}=useSidebar();return <SidebarMenuButton className="nav-button" isActive={active} onClick={()=>{onSelect();if(isMobile)setOpenMobile(false);}}>{children}</SidebarMenuButton>;}
export default function Portal(){
 const {data,error,auth,busy,act,refresh}=useWorkspace(); const [selected,setSelected]=useState<string|null>(null); const [status,setStatus]=useState('All statuses');const [ward,setWard]=useState(ALL_WARDS);const [cf,setCf]=useState<FilterState>(emptyFilters); const [page,setPage]=useState('Overview'); const [query,setQuery]=useState('');const [range,setRange]=useState<DateRange>(()=>makeRange(DEFAULT_PRESET));useEffect(()=>{try{setRange(parseStoredRange(window.sessionStorage.getItem(RANGE_STORAGE_KEY)));}catch{/* storage unavailable: keep this month */}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_complaints',description:'Filter the visible complaint workbench by search text.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw new Error('Invalid search query');setPage('Complaints');setCf(prev=>({...prev,query:input.query}));return {query:input.query};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 useEffect(()=>{if(data&&page!=='My profile'&&!data.viewer?.permissions.includes(pagePermission[page]))setPage(nav.find(([name])=>data.viewer?.permissions.includes(pagePermission[name]))?.[0]??'No access');},[data,page]);
 /* Complaints page: the shared filter toolbar (search, status, priority, category, department, ward, progress, overdue, created between) narrows every complaint; paging and CSV use the same filtered rows. */
 const allComplaints=data?.complaints; const complaintSpec=useMemo(()=>complaintFilterSpec(data?.settings.departments),[data?.settings.departments]); const filtered=useMemo(()=>applyFilters(allComplaints??[],cf,complaintSpec),[allComplaints,cf,complaintSpec]); const paged=usePaged(filtered,filterKey(cf),50);
 if(!data)return <LoadingWorkspace error={error} auth={auth} refresh={()=>void refresh()}/>;
 const visibleNav=nav.filter(([name])=>data.viewer?.permissions.includes(pagePermission[name]));const firstAdminItem=visibleNav.findIndex(([name])=>!WORKSPACE_PAGES.includes(name));
 const complaints=data.complaints; const pending=complaints.filter(c=>!['Closed','Rejected / Duplicate'].includes(c.status)); /* Ward filter on Overview (two or more wards only): it narrows the dashboard and its recent complaints; the sidebar count stays across all wards. */ const wardOptions=wardFilterOptions(data.wards,complaints); const wardFilterOn=showWardFilter(data.wards); const wardValue=wardFilterOn?resolveWardFilter(ward,wardOptions):ALL_WARDS; const inWard=filterByWard(complaints,wardValue); const wardName=wardOptions.find(o=>o.value===wardValue)?.label??''; const wardPicker=wardFilterOn?<WardFilter value={wardValue} onChange={setWard} options={wardOptions}/>:null;
 /* Overview: everything on the dashboard (stat cards, charts, recent complaints, attention card) covers complaints created inside the chosen date range, kept for this browser session. The Complaints page has its own filter toolbar, and its stat cards follow it. */
 const scope=filterByRange(inWard,range.from,range.to); const stats=summarize(page==='Overview'?scope:filtered); const chooseRange=(r:DateRange)=>{setRange(r);try{window.sessionStorage.setItem(RANGE_STORAGE_KEY,serializeRange(r));}catch{/* storage unavailable: the choice still applies for this visit */}};
 const shown=scope.filter(c=>(c.id+' '+c.title+' '+c.locality+' '+c.assignee).toLowerCase().includes(query.toLowerCase())&&(status==='All statuses'||c.status===status));
 const filterOptions=complaintFilterOptions({categories:data.categories,wards:data.wards,departments:data.settings.departments,complaints,statuses});
 const complaintFilters:FilterDef[]=[
  {key:'status',label:'Status',allLabel:'All statuses',options:filterOptions.status},
  {key:'priority',label:'Priority',allLabel:'All priorities',options:filterOptions.priority},
  {key:'category',label:'Category',allLabel:'All categories',options:filterOptions.category},
  {key:'department',label:'Department',allLabel:'All departments',options:filterOptions.department},
  ...(filterOptions.ward.length?[{key:'ward',label:'Ward',allLabel:'All wards',options:filterOptions.ward} as FilterDef]:[]),
  {key:'stage',label:'Progress',allLabel:'All progress',options:filterOptions.stage},
  {key:'overdue',label:'Resolution target',allLabel:'All complaints',options:filterOptions.overdue},
  {type:'dateRange',key:'created',label:'Created between'},
 ];
 return <SidebarProvider style={{'--sidebar-width':'248px'} as React.CSSProperties}>
 <Sidebar className="main-sidebar"><SidebarHeader><a href="/" className="brand"><img src="/samadhan-logo.png" alt="SAMADHAN समाधान"/><span><b>SAMADHAN</b><small>जनता की बात, समाधान के साथ</small></span></a></SidebarHeader><SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{visibleNav.map(([name,Icon],i)=><SidebarMenuItem key={name}>{i===firstAdminItem&&<p className="nav-label secondary-nav">ADMINISTRATION</p>}<NavItemButton active={page===name} onSelect={()=>setPage(name)}><Icon size={19}/><span>{name}</span>{name==='Complaints'&&<em>{pending.length}</em>}</NavItemButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent></Sidebar>
 <div className="portal"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><b className="topbar-title">{page}</b></div><div className="topbar-brand" aria-hidden="true"><img src="/samadhan-logo.png" alt=""/><span><b>SAMADHAN</b><small>जनता की बात, समाधान के साथ</small></span></div><div className="topbar-right"><UserMenu onOpenProfile={()=>setPage('My profile')}/></div></header><main className="main-content"><div className="page-heading"><div><div className="eyebrow">SEVA. SAHYOG. SAMADHAN.</div><h1>{page==='Overview'?'A better city starts with us.':page}</h1><p>{page==='Overview'?'Your ward at a glance. Keep services moving and residents informed.':'Manage civic services with a clear, accountable workflow.'}</p></div></div>
 {page==='Overview'&&data.viewer?.permissions.includes('complaints.read')&&<DateRangeControl value={range} onChange={chooseRange} matching={scope.length} scopeNote={wardValue===ALL_WARDS?'':wardName}>{wardPicker&&<label className="range-ward"><span>Ward</span>{wardPicker}</label>}</DateRangeControl>}{error&&<p className="error" role="alert">{error}</p>}
 {['Overview','Complaints'].includes(page)&&data.viewer?.permissions.includes('complaints.read')&&<section className="stat-grid">{[[ClipboardList,'Total complaints',stats.total,page==='Overview'?'Created in this period':hasActiveFilters(cf)?'Matching your filters':'Across all categories','blue'],[Clock3,'Needs attention',stats.open,`${stats.overdue} past resolution target`,'orange'],[Sprout,'In progress',stats.inProgress,'Work underway on the ground','purple'],[CheckCheck,'Resolved',stats.closed,`${stats.rate}% resolution rate`,'green']].map(([Icon,label,value,caption,tone]:any)=><div className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${tone}`}><Icon size={20}/></span></div><strong>{value}</strong><small>{caption}</small></div>)}</section>}
 {page==='Overview'&&<div className="dashboard-charts"><section className="panel trend-panel"><div className="panel-heading"><div><h2>Complaint activity</h2><p>{activityCaption(bucketUnit(dayCount(range.from,range.to)),range.from,range.to)}</p></div><span className="chart-legend"><i/> Received</span></div><ActivityChart complaints={scope} from={range.from} to={range.to}/></section><section className="panel category-panel"><div className="panel-heading"><div><h2>By category</h2><p>Complaints created {rangeLabel(range.from,range.to)}</p></div></div><CategoryChart complaints={scope} categories={data.categories}/></section></div>}
 {page==='My profile'?<MyProfile/>:page==='No access'?<p className="empty-state">No permissions assigned. Contact a Super Admin.</p>:page==='Categories'?<CategoryManager categories={data.categories} departments={data.settings.departments} busy={busy} act={act}/>:page==='Activities'?<ActivitiesManager key={page} data={data} act={act} busy={busy}/>:page==='App users'?<ResidentsManager key={page} data={data} act={act} busy={busy} refresh={refresh}/>:page==='Admin Users'?<AdminUsersManager key={page}/>:['Classifieds','City & places'].includes(page)?<CommunityPanel key={page} page={page} data={data} act={act} busy={busy}/>:!['Overview','Complaints'].includes(page)?<AdminPanel page={page} data={data} act={act} busy={busy}/>:page==='Complaints'?<div className="work-grid"><section className="panel complaints-panel"><div className="panel-heading"><div><h2>Complaint workbench</h2><p>Small actions. Visible progress.</p></div><button className="button" disabled={!filtered.length} onClick={()=>csvDownload(filtered)}><Download size={16}/>Export CSV</button></div><div style={{padding:'0 22px 8px'}}><FilterToolbar noun="complaints" filters={complaintFilters} state={cf} onChange={setCf} total={complaints.length} filtered={filtered.length} shown={paged.shown} searchPlaceholder="Search by ID, issue, locality or department…"/></div>{!complaints.length?<p className="empty-state">No complaints yet.</p>:!filtered.length?<FilterEmpty onClear={()=>setCf(emptyFilters())}/>:<><ComplaintRows rows={paged.rows} showWard={wardFilterOn} showDepartment onOpen={setSelected}/><ShowMore remaining={paged.remaining} size={paged.size} onMore={paged.more}/></>}</section></div>:<div className="work-grid"><section className="panel complaints-panel"><div className="panel-heading"><div><h2>Recent complaints</h2><p>Small actions. Visible progress.</p></div><button className="text-button" onClick={()=>setPage('Complaints')}>View all <ArrowRight size={16}/></button></div><div className="table-toolbar"><label className="search-box"><Search size={17}/><input aria-label="Search complaints" placeholder="Search by ID, issue or locality…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Choice label="Filter by status" value={status} onChange={setStatus} options={['All statuses',...statuses]}/><span className="record-count">{shown.length} records</span></div>{!shown.length&&<p className="empty-state">No complaints match these filters.</p>}<ComplaintRows rows={shown.slice(0,5)} showWard={wardFilterOn} onOpen={setSelected}/></section></div>}<footer className="portal-footer"><span>SAMADHAN <span className="note-divider">/</span> Better neighbourhoods, together.</span><span><ShieldCheck size={14}/> Accountable at every step</span></footer>
 </main></div><ComplaintDetail readOnly={!data.viewer?.permissions.includes('complaints.manage')} categories={data.categories} teams={data.settings.teams} departments={data.settings.departments} communications={data.communications} complaint={complaints.find(c=>c.id===selected)||null} onClose={()=>setSelected(null)} act={act} busy={busy}/></SidebarProvider>;
}
