import type {Workspace} from '../shared/domain';
import type {CommunityState} from './community-service';

/** User-requested demo content, also used by the one-time workspace upgrade. */
export function addDemoCommunity(state:Workspace&CommunityState,now=Date.now()){
 const startsAt=new Date(now-86400000).toISOString(),endsAt=new Date(now+180*86400000).toISOString();
 const ads=[
  {id:'sample-ad-market',title:'Weekend local makers market',titleHi:'सप्ताहांत स्थानीय हस्तशिल्प बाजार',description:'SAMPLE AD — Explore handmade crafts, home decor and local food at the demonstration community market. Saturday, 10 AM–6 PM. This is fictional preview content, not a real event.',descriptionHi:'नमूना विज्ञापन — हस्तशिल्प, सजावट और स्थानीय भोजन का बाजार। शनिवार सुबह 10 से शाम 6 बजे। यह काल्पनिक परीक्षण सामग्री है।',advertiser:'Demo Community Centre'},
  {id:'sample-ad-skills',title:'Computer skills for beginners',titleHi:'शुरुआती कंप्यूटर प्रशिक्षण',description:'SAMPLE AD — A demonstration listing for a four-week introductory computer course. View how the administration can publish learning opportunities for residents. No registration or payment is available.',descriptionHi:'नमूना विज्ञापन — चार सप्ताह का शुरुआती कंप्यूटर प्रशिक्षण। देखें कि प्रशासन नागरिकों के लिए अवसर कैसे प्रकाशित कर सकता है। पंजीकरण या भुगतान उपलब्ध नहीं है।',advertiser:'Demo Learning Centre'},
  {id:'sample-ad-garden',title:'Neighbourhood garden volunteers',titleHi:'मोहल्ले के उद्यान के लिए स्वयंसेवक',description:'SAMPLE AD — Join a fictional Sunday garden clean-up and planting activity at the sample civic park. This demonstrates a community notice; no real event is scheduled.',descriptionHi:'नमूना विज्ञापन — रविवार को उद्यान की सफाई और पौधारोपण का काल्पनिक कार्यक्रम। कोई वास्तविक आयोजन निर्धारित नहीं है।',advertiser:'Demo Residents Association'},
 ];
 state.classifieds??=[];state.places??=[];let adsAdded=0,placesAdded=0;
 for(const ad of ads)if(!state.classifieds.some(a=>a.id===ad.id)){state.classifieds.push({...ad,imageId:'',contactPhone:'',url:'',startsAt,endsAt,status:'published',publishedAt:new Date(now).toISOString()});adsAdded++;}
 const places=[
  {id:'sample-place-gate',name:'Heritage Gate · sample',nameHi:'विरासत द्वार · नमूना',description:'A fictional heritage landmark showing how a place can include its story, address and visitor information. Replace this entry with a verified landmark from your municipality.',descriptionHi:'काल्पनिक विरासत स्थल। यहां विवरण, पता और पर्यटकों की जानकारी दिखाई जाती है। इसे अपने नगर के सत्यापित स्थल से बदलें।',address:'Sample Heritage Road, demonstration ward',hours:'Sample hours: 9 AM–5 PM'},
  {id:'sample-place-park',name:'Civic Garden · sample',nameHi:'नगर उद्यान · नमूना',description:'A fictional neighbourhood garden with walking paths and a children’s play area. This sample illustrates an outdoor attraction listing; it is not a verified travel recommendation.',descriptionHi:'पैदल पथ और बच्चों के खेल क्षेत्र वाला काल्पनिक नगर उद्यान। यह केवल परीक्षण के लिए है।',address:'Sample Park Road, demonstration ward',hours:'Sample hours: 6 AM–8 PM'},
  {id:'sample-place-museum',name:'Town History Gallery · sample',nameHi:'नगर इतिहास दीर्घा · नमूना',description:'A fictional gallery featuring civic history, old photographs and local crafts. Administrators can add real images, source links and directions when verified information is available.',descriptionHi:'नगर इतिहास, पुरानी तस्वीरों और स्थानीय कला की काल्पनिक दीर्घा। प्रशासन सत्यापित जानकारी के साथ फोटो, स्रोत और मानचित्र जोड़ सकता है।',address:'Sample Civic Square, demonstration ward',hours:'Sample hours: Tuesday–Sunday, 10 AM–5 PM'},
 ];
 for(const [i,p] of places.entries())if(!state.places.some(x=>x.id===p.id)){state.places.push({...p,imageId:'',sourceUrl:'',mapUrl:'',published:true,sortOrder:i});placesAdded++;}
 // Preserve any real municipality information, even if it is currently a draft.
 if(!state.municipality?.name&&!state.municipality?.about&&!state.municipality?.history)state.municipality={name:`${state.settings.city} · sample city guide`,nameHi:'अपना नगर · नमूना परिचय',district:state.settings.city,state:'Rajasthan',about:'DEMO CONTENT — This page shows how the municipality can introduce its services, neighbourhoods and places to visit. The entries below are fictional examples for testing and can be edited in Admin → City & places.',aboutHi:'नमूना सामग्री — नगर की सेवाएं, मोहल्ले और घूमने के स्थान यहां दिखेंगे। नीचे की प्रविष्टियां काल्पनिक परीक्षण उदाहरण हैं।',history:'SAMPLE HISTORY — In this fictional example, a small market settlement grows around a civic square, later adding gardens, a library and community facilities. This text demonstrates the history section and is not a factual account of Jaipur or any municipality.',historyHi:'नमूना इतिहास — इस काल्पनिक उदाहरण में नगर के चौक के आसपास बाजार, उद्यान, पुस्तकालय और सामुदायिक सुविधाएं विकसित होती हैं। यह जयपुर या किसी नगर का वास्तविक इतिहास नहीं है।',sourceUrl:'',published:true};
 return {adsAdded,placesAdded};
}
