import fs from 'node:fs';
const path='app/portal.tsx';let s=fs.readFileSync(path,'utf8');
s=s.replace("import { useState }", "import { useState, useEffect }");
s=s.replace("import { seedWorkspace, type Complaint, type Workspace }", "import { statuses, categories, type Complaint, type Workspace }");
s=s.replace("export function StatusBadge", "import {useWorkspace} from './use-workspace';\nimport {LoadingWorkspace,ComplaintDetail,Choice,AdminPanel,csvDownload} from './admin-panels';\nexport function StatusBadge");
s=s.replace("const [data,setData]=useState<Workspace>(()=>seedWorkspace());", "const {data,error,auth,busy,act,refresh}=useWorkspace(); const [selected,setSelected]=useState<string|null>(null); const [status,setStatus]=useState('All statuses');const [category,setCategory]=useState('All categories');const [overdueOnly,setOverdueOnly]=useState(false);");
s=s.replace('const complaints=data.complaints;',`useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_complaints',description:'Filter the visible complaint workbench by search text.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw new Error('Invalid search query');setPage('Complaints');setQuery(input.query);return {query:input.query};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 if(!data)return <LoadingWorkspace error={error} auth={auth} refresh={()=>void refresh()}/>;
 const complaints=data.complaints;`);
s=s.replace(".includes(query.toLowerCase()));", ".includes(query.toLowerCase())&&(status==='All statuses'||c.status===status)&&(category==='All categories'||c.category===category)&&(!overdueOnly||(!['Closed','Rejected / Duplicate'].includes(c.status)&&new Date(c.dueAt)<new Date())));");
s=s.replace('<div className="pilot-note">', '{error&&<p className="error" role="alert">{error}</p>}<div className="pilot-note">');
s=s.replace('<div className="work-grid">', "{!['Overview','Complaints'].includes(page)?<AdminPanel page={page} data={data} act={act} busy={busy}/>:<div className=\"work-grid\">");
s=s.replace('</aside>}</div><footer', '</aside>}</div>}<footer');
s=s.replace('<span className="record-count">', '<Choice label="Filter by status" value={status} onChange={setStatus} options={[\'All statuses\',...statuses]}/>{page===\'Complaints\'&&<><Choice label="Filter by category" value={category} onChange={setCategory} options={[\'All categories\',...categories]}/><button className="button" onClick={()=>csvDownload(shown)}>Export CSV</button></>}<span className="record-count">');
s=s.replace('<b className="complaint-title">{c.title}</b>', '<button className="complaint-title" onClick={()=>setSelected(c.id)}>{c.title}</button>');
s=s.replace('<TableCell><ChevronRight size={17}/></TableCell>', '<TableCell><button aria-label={`Open ${c.id}`} onClick={()=>setSelected(c.id)}><ChevronRight size={17}/></button></TableCell>');
s=s.replace('<button onClick={()=>setPage(\'Complaints\')}>Review', '<button onClick={()=>{setPage(\'Complaints\');setOverdueOnly(true);}}>Review');
s=s.replace('<Table><TableHeader>', '{overdueOnly&&<button className="filter-notice" onClick={()=>setOverdueOnly(false)}>Showing overdue complaints · Clear filter ×</button>}{!shown.length&&<p className="empty-state">No complaints match these filters.</p>}<Table><TableHeader>');
s=s.replace('</main></div></SidebarProvider>', '</main></div><ComplaintDetail complaint={complaints.find(c=>c.id===selected)||null} onClose={()=>setSelected(null)} act={act} busy={busy}/></SidebarProvider>');
fs.writeFileSync(path,s);
