import {loadWorkspace} from '@/lib/workspaces';
import {canReadMedia} from '@/lib/media-access';
import { env } from 'cloudflare:workers';
import { identity, database, apiError, assertOrigin } from '@/lib/server';
import { ServiceError } from '@/lib/service';
export const dynamic='force-dynamic';
// A registration token (30 minutes, issued after OTP verification) may upload the resident's photo before the profile exists; the upload is owned by the mobile-derived resident id.
export async function POST(request:Request){try{assertOrigin(request);const who=await identity(request,{allowRegistration:true});if(!env.BUCKET)throw new ServiceError('Evidence storage is unavailable.',503);
// Resident bearer tokens are rate limited by total uploads (a registration token far lower), so a leaked or test-mode token cannot fill storage.
if(who.session){const quota=who.session.kind==='registration'?10:300;const used=await database().prepare('SELECT COUNT(*) AS n FROM media WHERE owner = ? AND uploader = ?').bind(who.owner,who.residentId).first<{n:number}>();if((used?.n??0)>=quota)throw new ServiceError('Upload limit reached. Contact the ward office.',429);}
if(Number(request.headers.get('content-length'))>6*1024*1024)throw new ServiceError('Photographs must be smaller than 5 MB.',413);const form=await request.formData();const file=form.get('file');if(!(file instanceof File)||file.size>5*1024*1024||file.size<12)throw new ServiceError('Choose a JPG, PNG or WebP photograph under 5 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=bytes.slice(0,8).every((v,i)=>v===[137,80,78,71,13,10,26,10][i]);const webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';const type=jpg?'image/jpeg':png?'image/png':webp?'image/webp':null;if(!type)throw new ServiceError('Unsupported image contents. Use JPG, PNG or WebP.');const id=crypto.randomUUID();await env.BUCKET.put(id,bytes,{httpMetadata:{contentType:type}});await database().prepare('INSERT INTO media (id, owner, content_type, uploader) VALUES (?, ?, ?, ?)').bind(id,who.owner,type,who.residentId).run();return Response.json({id});}catch(e){return apiError(e);}}
export async function GET(request:Request){try{const who=await identity(request);const id=new URL(request.url).searchParams.get('id');const row=await database().prepare('SELECT content_type,uploader FROM media WHERE id = ? AND owner = ?').bind(id,who.owner).first<{content_type:string;uploader:string|null}>();if(!row||!env.BUCKET)throw new ServiceError('Photograph not found.',404);const state=JSON.parse((await loadWorkspace(who.owner)).body);if(!canReadMedia(state,who,id!,row.uploader))throw new ServiceError('Photograph not found.',404);
// Revalidate every banner read so disabling artwork also revokes access for a client with a cached copy. Access is checked above
// (a banner hidden from residents answers 404 even to a conditional request); stored media is immutable per id, so the id is the ETag.
const banner=!!state.settings?.brandingBanners?.some((b:{imageId:string})=>b.imageId===id);const etag=`"${id}"`;
const cacheHeaders:Record<string,string>=banner?{'Cache-Control':'private, max-age=0, must-revalidate',ETag:etag,Vary:'Authorization, Cookie'}:{'Cache-Control':'private, no-store'};
if(banner&&request.headers.get('If-None-Match')?.split(',').some(v=>v.trim().replace(/^W\//,'')===etag))return new Response(null,{status:304,headers:{...cacheHeaders,'X-Content-Type-Options':'nosniff'}});
const file=await env.BUCKET.get(id!);if(!file)throw new ServiceError('Photograph not found.',404);return new Response(file.body,{headers:{'Content-Type':row.content_type,'X-Content-Type-Options':'nosniff',...cacheHeaders}});}catch(e){return apiError(e);}}
